version: '3.8'

services:
  # ── Core infra ────────────────────────────────────────────────
  postgres:
    image: postgres:16
    container_name: postgres_interview
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: interview_prep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-backup-data:/var/lib/postgresql/backup
    networks: [ app-network ]
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks: [ app-network ]
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: [ app-network ]
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # ── Optional extras (enable with profile "extras") ────────────
  gptj:
    profiles: [ "local" ]
    image: localai/localai:latest
    container_name: localai_gptj
    ports:
      - "8086:8080"
    volumes:
      - ./models:/models
    environment:
      OPENAI_API_KEY: your-key
      MODELS_PATH: /models
      DEBUG: "true"
    networks: [ app-network ]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080/v1/models" ]
      interval: 10s
      retries: 5

  minio:
    profiles: [ "local" ]
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks: [ app-network ]
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  postgres-backup-data:
  minio_data:
