package com.vladte.devhack.common.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * DTO for User entity.
 * Implements BaseDTO for consistency with other DTOs.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "User data transfer object")
public class UserDTO implements BaseDTO {

    @Schema(description = "Unique identifier", accessMode = Schema.AccessMode.READ_ONLY)
    private UUID id;

    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    @Size(max = 100, message = "Email must be less than 100 characters")
    @Schema(description = "User's email address", example = "user@example.com", required = true)
    private String email;

    // Password is intentionally excluded from DTO for security reasons

    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 50, message = "Name must be between 2 and 50 characters")
    @Schema(description = "User's name", example = "John Doe", required = true)
    private String name;

    @Schema(description = "User's role", example = "USER", accessMode = Schema.AccessMode.READ_ONLY)
    private String role;

    // CV fields
    @Schema(description = "CV file URL", accessMode = Schema.AccessMode.READ_ONLY)
    private String cvFileHref;

    @Schema(description = "CV file name", accessMode = Schema.AccessMode.READ_ONLY)
    private String cvFileName;

    @Schema(description = "CV file MIME type", accessMode = Schema.AccessMode.READ_ONLY)
    private String cvFileType;

    @Schema(description = "CV file size in bytes", accessMode = Schema.AccessMode.READ_ONLY)
    private Long cvFileSize;

    @Schema(description = "CV file upload timestamp", accessMode = Schema.AccessMode.READ_ONLY)
    private LocalDateTime cvUploadedAt;

    @Schema(description = "Whether CV was successfully parsed", accessMode = Schema.AccessMode.READ_ONLY)
    private Boolean cvParsedSuccessfully;

    // AI usage fields
    @Schema(description = "Whether AI usage is allowed for this user", example = "false")
    private Boolean aiUsageAllowed;

    @Schema(description = "Whether AI features are enabled for this user", example = "false")
    private Boolean aiUsageEnabled;

    @Schema(description = "User's preferred language for AI interactions", example = "en")
    private String aiPreferredLanguage;

    @Schema(description = "CV score determined by AI", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer aiCvScore;

    @Schema(description = "Skills summary generated by AI", accessMode = Schema.AccessMode.READ_ONLY)
    private String aiSkillsSummary;

    @Schema(description = "CV improvement suggestions from AI", accessMode = Schema.AccessMode.READ_ONLY)
    private String aiSuggestedImprovements;

    // Visibility setting
    @Schema(description = "Whether the user's profile is visible to recruiters", example = "true")
    private Boolean isVisibleToRecruiters;

    @Schema(description = "IDs of answers created by this user", accessMode = Schema.AccessMode.READ_ONLY)
    private List<UUID> answerIds = new ArrayList<>();

    @Schema(description = "IDs of notes created by this user", accessMode = Schema.AccessMode.READ_ONLY)
    private List<UUID> noteIds = new ArrayList<>();

    @Schema(description = "IDs of vacancy responses created by this user", accessMode = Schema.AccessMode.READ_ONLY)
    private List<UUID> vacancyResponseIds = new ArrayList<>();

    @Schema(description = "Creation timestamp", accessMode = Schema.AccessMode.READ_ONLY)
    private LocalDateTime createdAt;
}
